dist: xenial

git:
  depth: false

addons:
  hosts:
    - magento2.docker

services:
  - docker

language: php

stages:
  - test

env:
  - MAGENTO_CLOUD_PROJECT=travis-testing

jobs:
  include:
    - stage: test
      php: '7.1'
      env:
        - TEST_SUITE=functional-ee
    - php: '7.2'
      env:
        - TEST_SUITE=functional-ee
    - php: '7.3'
      env:
        - TEST_SUITE=functional-ee
    - php: '7.1'
      env:
        - TEST_SUITE=functional-ce
    - php: '7.2'
      env:
        - TEST_SUITE=functional-ce
    - php: '7.3'
      env:
        - TEST_SUITE=functional-ce

install:
  - composer config http-basic.repo.magento.com ${REPO_USERNAME_CE} ${REPO_PASSWORD_CE}
  - composer config github-oauth.github.com ${GITHUB_TOKEN}
  - if [ -n "${MCD_VERSION}" ]; then composer config repositories.mcd git git@github.com:magento/magento-cloud-docker.git && composer require "magento/magento-cloud-docker:${MCD_VERSION}" --no-update; fi;
  - if [ -n "${MCP_VERSION}" ]; then composer config repositories.mcp git git@github.com:magento-mpi/magento-cloud-patches.git && composer require "magento/magento-cloud-patches:${MCP_VERSION}" --no-update; fi;
  - composer update -n --no-suggest

before_script:
  - sudo sysctl -w vm.max_map_count=262144
  - cp codeception.dist.yml codeception.yml
  - sed -i "s/https:\/\/github.com\/magento\/magento-cloud-patches.git/https:\/\/github.com\/magento-mpi\/magento-cloud-patches.git/" codeception.yml
  - if [ $TEST_SUITE == "functional-ce" ]; then sed -i "s/REPO_USERNAME/REPO_USERNAME_CE/" codeception.yml && sed -i "s/REPO_PASSWORD/REPO_PASSWORD_CE/" codeception.yml; fi;

script:
  - if [ $TRAVIS_SECURE_ENV_VARS == "true" ] && [ $TEST_SUITE == "functional-ee" ]; then ./tests/travis/functional-ee.sh; fi;
  - if [ $TEST_SUITE == "functional-ce" ]; then ./tests/travis/functional-ce.sh; fi;
